<?php

use App\SuraList;
use Illuminate\Database\Seeder;

class SuraListTableSeeder extends Seeder
{
   /**
    * Run the database seeds.
    *
    * @return void
    */
   public function run()
   {

      $suraList = array(
         array("id" => 1, "name" => "الفاتحة", "english_name" => "Al-Faatiha", "english_ayahs_count" => "verse-7", "bangla_name" => "আল-ফাতিহা", "bangla_ayahs_count" => "আয়াত-৭"),
         array("id" => 2, "name" => "البقرة", "english_name" => "Al-Baqarah", "english_ayahs_count" => "verse-286", "bangla_name" => "আল-বাক্বারাহ্", "bangla_ayahs_count" => "আয়াত-২৮৬"),
         array("id" => 3, "name" => "آل عمران", "english_name" => "Al-Imran", "english_ayahs_count" => "verse-200", "bangla_name" => "আল-ইমরান", "bangla_ayahs_count" => "আয়াত-২০০"),
         array("id" => 4, "name" => "النساء", "english_name" => "An-Nisa", "english_ayahs_count" => "verse-176", "bangla_name" => "আন-নিসা", "bangla_ayahs_count" => "আয়াত-১৭৬"),
         array("id" => 5, "name" => "المائدة", "english_name" => "Al-Ma'idah", "english_ayahs_count" => "verse-120", "bangla_name" => "আল-মায়েদাহ্", "bangla_ayahs_count" => "আয়াত-১২০"),
         array("id" => 6, "name" => "الأنعام", "english_name" => "Al-An'am", "english_ayahs_count" => "verse-165", "bangla_name" => "আল-আন‘আম", "bangla_ayahs_count" => "আয়াত-১৬৫"),
         array("id" => 7, "name" => "الأعراف", "english_name" => "Al-A'raf", "english_ayahs_count" => "verse-206", "bangla_name" => "আল-আ‘রাফ", "bangla_ayahs_count" => "আয়াত-২০৬"),
         array("id" => 8, "name" => "الأنفال", "english_name" => "Al-Anfal", "english_ayahs_count" => "verse-75", "bangla_name" => "আল-আনফাল", "bangla_ayahs_count" => "আয়াত-৭৫"),
         array("id" => 9, "name" => "التوبة", "english_name" => "At-Taubah", "english_ayahs_count" => "verse-129", "bangla_name" => "আত-তাওবাহ্", "bangla_ayahs_count" => "আয়াত-১২৯"),
         array("id" => 10, "name" => "يونس", "english_name" => "Yunus", "english_ayahs_count" => "verse-109", "bangla_name" => "ইউনুস", "bangla_ayahs_count" => "আয়াত-১০৯"),
         array("id" => 11, "name" => "هود", "english_name" => "Hood", "english_ayahs_count" => "verse-123", "bangla_name" => "হূদ", "bangla_ayahs_count" => "আয়াত-১২৩"),
         array("id" => 12, "name" => "يوسف", "english_name" => "Yusuf", "english_ayahs_count" => "verse-111", "bangla_name" => "ইউসুফ", "bangla_ayahs_count" => "আয়াত-১১১"),
         array("id" => 13, "name" => "الرعد", "english_name" => "Ar-Ra'd", "english_ayahs_count" => "verse-43", "bangla_name" => "আর-রা‘দ", "bangla_ayahs_count" => "আয়াত-৪৩"),
         array("id" => 14, "name" => "إبراهيم", "english_name" => "Ibrahim", "english_ayahs_count" => "verse-52", "bangla_name" => "ইব্রাহীম", "bangla_ayahs_count" => "আয়াত-৫২"),
         array("id" => 15, "name" => "الحجر", "english_name" => "Al-Hijr", "english_ayahs_count" => "verse-99", "bangla_name" => "আল-হিজর", "bangla_ayahs_count" => "আয়াত-৯৯"),
         array("id" => 16, "name" => "النحل", "english_name" => "An-Nahl", "english_ayahs_count" => "verse-128", "bangla_name" => "আন-নাহ্‌ল", "bangla_ayahs_count" => "আয়াত-১২৮"),
         array("id" => 17, "name" => "الإسراء", "english_name" => "Al-Isra", "english_ayahs_count" => "verse-111", "bangla_name" => "আল-ইসরা", "bangla_ayahs_count" => "আয়াত-১১১"),
         array("id" => 18, "name" => "الكهف", "english_name" => "Al-Kahf", "english_ayahs_count" => "verse-110", "bangla_name" => "আল-কাহফ", "bangla_ayahs_count" => "আয়াত-১১০"),
         array("id" => 19, "name" => "مريم", "english_name" => "Maryam", "english_ayahs_count" => "verse-98", "bangla_name" => "মারইয়াম", "bangla_ayahs_count" => "আয়াত-৯৮"),
         array("id" => 20, "name" => "طه", "english_name" => "TaHa", "english_ayahs_count" => "verse-135", "bangla_name" => "ত্বা-হা", "bangla_ayahs_count" => "আয়াত-১৩৫"),
         array("id" => 21, "name" => "الأنبياء", "english_name" => "Al-Anbiya", "english_ayahs_count" => "verse-112", "bangla_name" => "আল-আম্বিয়া", "bangla_ayahs_count" => "আয়াত-১১২"),
         array("id" => 22, "name" => "الحج", "english_name" => "Al-Hajj", "english_ayahs_count" => "verse-78", "bangla_name" => "আল-হাজ্জ", "bangla_ayahs_count" => "আয়াত-৭৮"),
         array("id" => 23, "name" => "المؤمنون", "english_name" => "Al-Mu'minun", "english_ayahs_count" => "verse-118", "bangla_name" => "আল-মু’মিনূন", "bangla_ayahs_count" => "আয়াত-১১৮"),
         array("id" => 24, "name" => "النور", "english_name" => "An-Nur", "english_ayahs_count" => "verse-64", "bangla_name" => "আন-নূর", "bangla_ayahs_count" => "আয়াত-৬৪"),
         array("id" => 25, "name" => "الفرقان", "english_name" => "Al-Furqan", "english_ayahs_count" => "verse-77", "bangla_name" => "আল-ফুরক্বান", "bangla_ayahs_count" => "আয়াত-৭৭"),
         array("id" => 26, "name" => "الشعراء", "english_name" => "Ash-Shu'ara", "english_ayahs_count" => "verse-227", "bangla_name" => "আশ-শু‘আরা", "bangla_ayahs_count" => "আয়াত-২২৭"),
         array("id" => 27, "name" => "النمل", "english_name" => "An-Naml", "english_ayahs_count" => "verse-93", "bangla_name" => "আন-নামল", "bangla_ayahs_count" => "আয়াত-৯৩"),
         array("id" => 28, "name" => "القصص", "english_name" => "Al-Qasas", "english_ayahs_count" => "verse-88", "bangla_name" => "আল-ক্বাসাস", "bangla_ayahs_count" => "আয়াত-৮৮"),
         array("id" => 29, "name" => "العنكبوت", "english_name" => "Al-Ankabut", "english_ayahs_count" => "verse-69", "bangla_name" => "আল-‘আনকাবূত", "bangla_ayahs_count" => "আয়াত-৬৯"),
         array("id" => 30, "name" => "الروم", "english_name" => "Ar-Room", "english_ayahs_count" => "verse-60", "bangla_name" => "আর-রূম", "bangla_ayahs_count" => "আয়াত-৬০"),
         array("id" => 31, "name" => "لقمان", "english_name" => "Luqman", "english_ayahs_count" => "verse-34", "bangla_name" => "লুক্বমান", "bangla_ayahs_count" => "আয়াত-৩৪"),
         array("id" => 32, "name" => "السجدة", "english_name" => "As-Sajdah", "english_ayahs_count" => "verse-30", "bangla_name" => "আস-সাজদা", "bangla_ayahs_count" => "আয়াত-৩০"),
         array("id" => 33, "name" => "الأحزاب", "english_name" => "Al-Ahzab", "english_ayahs_count" => "verse-73", "bangla_name" => "আল-আহযাব", "bangla_ayahs_count" => "আয়াত-৭৩"),
         array("id" => 34, "name" => "سبأ", "english_name" => "Saba", "english_ayahs_count" => "verse-54", "bangla_name" => "সাবা", "bangla_ayahs_count" => "আয়াত-৫৪"),
         array("id" => 35, "name" => "فاطر", "english_name" => "Fatir", "english_ayahs_count" => "verse-45", "bangla_name" => "ফাতের", "bangla_ayahs_count" => "আয়াত-৪৫"),
         array("id" => 36, "name" => "يس", "english_name" => "Yaseen", "english_ayahs_count" => "verse-83", "bangla_name" => "ইয়াসীন", "bangla_ayahs_count" => "আয়াত-৮৩"),
         array("id" => 37, "name" => "الصافات", "english_name" => "As-Saffat", "english_ayahs_count" => "verse-182", "bangla_name" => "আস-সাফ্‌ফাত", "bangla_ayahs_count" => "আয়াত-১৮২"),
         array("id" => 38, "name" => "سُورَةُ صٓ", "english_name" => "Saad", "english_ayahs_count" => "verse-88", "bangla_name" => "সদ", "bangla_ayahs_count" => "আয়াত-৮৮"),
         array("id" => 39, "name" => "الزمر", "english_name" => "Az-Zumar", "english_ayahs_count" => "verse-75", "bangla_name" => "আয-যুমার", "bangla_ayahs_count" => "আয়াত-৭৫"),
         array("id" => 40, "name" => "غافر", "english_name" => "Ghafir", "english_ayahs_count" => "verse-85", "bangla_name" => "গাফের", "bangla_ayahs_count" => "আয়াত-৮৫"),
         array("id" => 41, "name" => "فصلت", "english_name" => "Fussilat", "english_ayahs_count" => "verse-54", "bangla_name" => "ফুসসিলাত", "bangla_ayahs_count" => "আয়াত-54"),
         array("id" => 42, "name" => "الشورى", "english_name" => "Ash-Shura", "english_ayahs_count" => "verse-53", "bangla_name" => "আশ-শূরা", "bangla_ayahs_count" => "আয়াত-৫৩"),
         array("id" => 43, "name" => "الزخرف", "english_name" => "Az-Zukhruf", "english_ayahs_count" => "verse-89", "bangla_name" => "আয-যুখরুফ", "bangla_ayahs_count" => "আয়াত-৮৯"),
         array("id" => 44, "name" => "الدّخان", "english_name" => "Ad-Dukhan", "english_ayahs_count" => "verse-59", "bangla_name" => "আদ-দুখান", "bangla_ayahs_count" => "আয়াত-৫৯"),
         array("id" => 45, "name" => "الجاثية", "english_name" => "Al-Jathiya", "english_ayahs_count" => "verse-37", "bangla_name" => "আল-জাসিয়া", "bangla_ayahs_count" => "আয়াত-৩৭"),
         array("id" => 46, "name" => "الأحقاف", "english_name" => "Al-Ahqaf", "english_ayahs_count" => "verse-35", "bangla_name" => "আল-আহক্বাফ", "english_ayahs_count" => "আয়াত-৭"),
         array("id" => 47, "name" => "محمد", "english_name" => "Muhammad", "english_ayahs_count" => "verse-38", "bangla_name" => "মুহাম্মাদ", "bangla_ayahs_count" => "আয়াত-৩৮"),
         array("id" => 48, "name" => "الفتح", "english_name" => "Al-Fath", "english_ayahs_count" => "verse-29", "bangla_name" => "আল-ফাতহ", "bangla_ayahs_count" => "আয়াত-২৯"),
         array("id" => 49, "name" => "الحجرات", "english_name" => "Al-Hujurat", "english_ayahs_count" => "verse-18", "bangla_name" => "আল-হুজুরাত", "bangla_ayahs_count" => "আয়াত-১৮"),
         array("id" => 50, "name" => "ق", "english_name" => "Qaf", "english_ayahs_count" => "verse-45", "bangla_name" => "ক্বাফ", "bangla_ayahs_count" => "আয়াত-৪৫"),
         array("id" => 51, "name" => "الذاريات", "english_name" => "Az-Zariyat", "english_ayahs_count" => "verse-60", "bangla_name" => "আয-যারিয়াত", "bangla_ayahs_count" => "আয়াত-৬০"),
         array("id" => 52, "name" => "الطور", "english_name" => "At-Tur", "english_ayahs_count" => "verse-49", "bangla_name" => "আত-তূর", "bangla_ayahs_count" => "আয়াত-৪৯"),
         array("id" => 53, "name" => "النجم", "english_name" => "An-Najm", "english_ayahs_count" => "verse-62", "bangla_name" => "আন-নাজম", "bangla_ayahs_count" => "আয়াত-৬২"),
         array("id" => 54, "name" => "القمر", "english_name" => "Al-Qamar", "english_ayahs_count" => "verse-55", "bangla_name" => "আল-ক্বামার", "bangla_ayahs_count" => "আয়াত-৫৫"),
         array("id" => 55, "name" => "الرحمن", "english_name" => "Ar-Rahman", "english_ayahs_count" => "verse-78", "bangla_name" => "আর-রাহমান", "bangla_ayahs_count" => "আয়াত-৭৮"),
         array("id" => 56, "name" => "الواقعة", "english_name" => "Al-Waqi'ah", "english_ayahs_count" => "verse-96", "bangla_name" => "আল-ওয়াক্বি‘আহ", "english_ayahs_count" => "আয়াত-৭"),
         array("id" => 57, "name" => "الحديد", "english_name" => "Al-Hadid", "english_ayahs_count" => "verse-29", "bangla_name" => "আল-হাদীদ", "bangla_ayahs_count" => "আয়াত-২৯"),
         array("id" => 58, "name" => "المجادلة", "english_name" => "Al-Mujadilah", "english_ayahs_count" => "verse-22", "bangla_name" => "আল-মুজাদালাহ্", "bangla_ayahs_count" => "আয়াত-২২"),
         array("id" => 59, "name" => "الحشر", "english_name" => "Al-Hashr", "english_ayahs_count" => "verse-24", "bangla_name" => "আল-হাশর", "bangla_ayahs_count" => "আয়াত-২৪"),
         array("id" => 60, "name" => "الممتحنة", "english_name" => "Al-Mumtahinah", "english_ayahs_count" => "verse-13", "bangla_name" => "আল-মুমতাহিনা", "bangla_ayahs_count" => "আয়াত-১৩"),
         array("id" => 61, "name" => "الصف", "english_name" => "As-Saff", "english_ayahs_count" => "verse-14", "bangla_name" => "আস-সাফ", "bangla_ayahs_count" => "আয়াত-১৪"),
         array("id" => 62, "name" => "الجمعة", "english_name" => "Al-Jumu'ah", "english_ayahs_count" => "verse-11", "bangla_name" => "আল-জুমু‘আ", "bangla_ayahs_count" => "আয়াত-১১"),
         array("id" => 63, "name" => "المنافقون", "english_name" => "Al-Munafiqun", "english_ayahs_count" => "verse-11", "bangla_name" => "আল-মুনাফিক্বূন", "bangla_ayahs_count" => "আয়াত-১১"),
         array("id" => 64, "name" => "التغابن", "english_name" => "At-Taghabun", "english_ayahs_count" => "verse-18", "bangla_name" => "আত-তাগাবুন", "bangla_ayahs_count" => "আয়াত-১৮"),
         array("id" => 65, "name" => "الطلاق", "english_name" => "At-Talaq", "english_ayahs_count" => "verse-12", "bangla_name" => "আত-ত্বালাক", "bangla_ayahs_count" => "আয়াত-১২"),
         array("id" => 66, "name" => "التحريم", "english_name" => "At-Tahrim", "english_ayahs_count" => "verse-12", "bangla_name" => "আত-তাহরীম", "bangla_ayahs_count" => "আয়াত-১২"),
         array("id" => 67, "name" => "الملك", "english_name" => "Al-Mulk", "english_ayahs_count" => "verse-30", "bangla_name" => "আল-মুলক", "bangla_ayahs_count" => "আয়াত-৩০"),
         array("id" => 68, "name" => "القلم", "english_name" => "Al-Qalam", "english_ayahs_count" => "verse-52", "bangla_name" => "আল-ক্বালাম", "bangla_ayahs_count" => "আয়াত-৫২"),
         array("id" => 69, "name" => "الحاقة", "english_name" => "Al-Haqqah", "english_ayahs_count" => "verse-52", "bangla_name" => "আল-হাক্কাহ্", "bangla_ayahs_count" => "আয়াত-৫২"),
         array("id" => 70, "name" => "المعارج", "english_name" => "Al-Ma'arij", "english_ayahs_count" => "verse-44", "bangla_name" => "আল-মা‘আরেজ", "bangla_ayahs_count" => "আয়াত-৪৪"),
         array("id" => 71, "name" => "نوح", "english_name" => "Nooh", "english_ayahs_count" => "verse-28", "bangla_name" => "নূহ", "bangla_ayahs_count" => "আয়াত-২৮"),
         array("id" => 72, "name" => "الجن", "english_name" => "Al-Jinn", "english_ayahs_count" => "verse-28", "bangla_name" => "আল-জিন্ন", "bangla_ayahs_count" => "আয়াত-২৮"),
         array("id" => 73, "name" => "المزمل", "english_name" => "Al-Muzzammil", "english_ayahs_count" => "verse-20", "bangla_name" => "আল-মুযযাম্মিল", "bangla_ayahs_count" => "আয়াত-২০"),
         array("id" => 74, "name" => "المدثر", "english_name" => "Al-Muddaththir", "english_ayahs_count" => "verse-56", "bangla_name" => "আল-মুদ্দাস্‌সির", "bangla_ayahs_count" => "আয়াত-৫৬"),
         array("id" => 75, "name" => "القيامة", "english_name" => "Al-Qiyamah", "english_ayahs_count" => "verse-40", "bangla_name" => "আল-ক্বিয়ামাহ্‌", "bangla_ayahs_count" => "আয়াত-৪০"),
         array("id" => 76, "name" => "الإنسان", "english_name" => "Al-Insan", "english_ayahs_count" => "verse-31", "bangla_name" => "আল-ইনসান", "bangla_ayahs_count" => "আয়াত-৩১"),
         array("id" => 77, "name" => "المرسلات", "english_name" => "Al-Mursalat", "english_ayahs_count" => "verse-50", "bangla_name" => "আল-মুরসালাত", "bangla_ayahs_count" => "আয়াত-৫০"),
         array("id" => 78, "name" => "النبأ", "english_name" => "An-Naba", "english_ayahs_count" => "verse-40", "bangla_name" => "আন-নাবা", "bangla_ayahs_count" => "আয়াত-৪০"),
         array("id" => 79, "name" => "النازعات", "english_name" => "An-Nazi'at", "english_ayahs_count" => "verse-46", "bangla_name" => "আন-নাযি‘আত", "bangla_ayahs_count" => "আয়াত-৪৬"),
         array("id" => 80, "name" => "عبس", "english_name" => "Abasa", "english_ayahs_count" => "verse-42", "bangla_name" => "আবাসা", "bangla_ayahs_count" => "আয়াত-৪২"),
         array("id" => 81, "name" => "التكوير", "english_name" => "At-Takwir", "english_ayahs_count" => "verse-29", "bangla_name" => "আত-তাকভীর", "bangla_ayahs_count" => "আয়াত-২৯"),
         array("id" => 82, "name" => "الإنفطار", "english_name" => "Al-Infitar", "english_ayahs_count" => "verse-19", "bangla_name" => "আল-ইনফিতার", "bangla_ayahs_count" => "আয়াত-১৯"),
         array("id" => 83, "name" => "المطففين", "english_name" => "Al-Mutaffifin", "english_ayahs_count" => "verse-36", "bangla_name" => "আল-মুতাফফিফীন", "bangla_ayahs_count" => "আয়াত-৩৬"),
         array("id" => 84, "name" => "الإنشقاق", "english_name" => "Al-Inshiqaq", "english_ayahs_count" => "verse-25", "bangla_name" => "আল-ইনশিক্বাক", "english_ayahs_count" => "আয়াত-৭"),
         array("id" => 85, "name" => "البروج", "english_name" => "Al-Buruj", "english_ayahs_count" => "verse-22", "bangla_name" => "আল-বুরূজ", "bangla_ayahs_count" => "আয়াত-২২"),
         array("id" => 86, "name" => "الطارق", "english_name" => "At-Tariq", "english_ayahs_count" => "verse-17", "bangla_name" => "আত-ত্বারেক", "bangla_ayahs_count" => "আয়াত-১৭"),
         array("id" => 87, "name" => "الأعلى", "english_name" => "Al-A'la", "english_ayahs_count" => "verse-19", "bangla_name" => "আল-আ‘লা", "bangla_ayahs_count" => "আয়াত-১৯"),
         array("id" => 88, "name" => "الغاشية", "english_name" => "Al-Ghashiyah", "english_ayahs_count" => "verse-26", "bangla_name" => "আল-গাশিয়াহ্", "bangla_ayahs_count" => "আয়াত-২৬"),
         array("id" => 89, "name" => "الفجر", "english_name" => "Al-Fajr", "english_ayahs_count" => "verse-30", "bangla_name" => "আল-ফাজর", "bangla_ayahs_count" => "আয়াত-৩০"),
         array("id" => 90, "name" => "البلد", "english_name" => "Al-Balad", "english_ayahs_count" => "verse-20", "bangla_name" => "আল-বালাদ", "bangla_ayahs_count" => "আয়াত-২০"),
         array("id" => 91, "name" => "الشمس", "english_name" => "Ash-Shams", "english_ayahs_count" => "verse-15", "bangla_name" => "আশ-শামস", "bangla_ayahs_count" => "আয়াত-১৫"),
         array("id" => 92, "name" => "الليل", "english_name" => "Al-Lail", "english_ayahs_count" => "verse-21", "bangla_name" => "আল-লাইল", "bangla_ayahs_count" => "আয়াত-২১"),
         array("id" => 93, "name" => "الضحى", "english_name" => "Ad-Duha", "english_ayahs_count" => "verse-11", "bangla_name" => "আদ্ব-দ্বুহা", "bangla_ayahs_count" => "আয়াত-১১"),
         array("id" => 94, "name" => "الشرح", "english_name" => "Ash-Sharh", "english_ayahs_count" => "verse-8", "bangla_name" => "আশ-শারহ", "bangla_ayahs_count" => "আয়াত-৮"),
         array("id" => 95, "name" => "التين", "english_name" => "At-Tin", "english_ayahs_count" => "verse-8", "bangla_name" => "আত-তীন", "bangla_ayahs_count" => "আয়াত-৮"),
         array("id" => 96, "name" => "العلق", "english_name" => "Al-Alaq", "english_ayahs_count" => "verse-19", "bangla_name" => "আল-আলাক্ব", "bangla_ayahs_count" => "আয়াত-১৯"),
         array("id" => 97, "name" => "القدر", "english_name" => "Al-Baiyinah", "english_ayahs_count" => "verse-5", "bangla_name" => "আল-ক্বাদর", "bangla_ayahs_count" => "আয়াত-৫"),
         array("id" => 98, "name" => "البينة", "english_name" => "Al-Baqarah", "english_ayahs_count" => "verse-8", "bangla_name" => "আল-বায়্যিনাহ্", "bangla_ayahs_count" => "আয়াত-৮"),
         array("id" => 99, "name" => "الزلزلة", "english_name" => "Az-Zalzalah", "english_ayahs_count" => "verse-8", "bangla_name" => "আয-যালযালাহ্", "bangla_ayahs_count" => "আয়াত-৮"),
         array("id" => 100, "name" => "العاديات", "english_name" => "Al-Adiyat", "english_ayahs_count" => "verse-11", "bangla_name" => "আল-আদিয়াত", "bangla_ayahs_count" => "আয়াত-১১"),
         array("id" => 101, "name" => "القارعة", "english_name" => "Al-Qari'ah", "english_ayahs_count" => "verse-11", "bangla_name" => "আল-ক্বারি‘আহ্", "bangla_ayahs_count" => "আয়াত-১১"),
         array("id" => 102, "name" => "التكاثر", "english_name" => "At-Takathur", "english_ayahs_count" => "verse-8", "bangla_name" => "আত-তাকাসুর", "bangla_ayahs_count" => "আয়াত-৮"),
         array("id" => 103, "name" => "العصر", "english_name" => "Al-Asr", "english_ayahs_count" => "verse-3", "bangla_name" => "আল-আসর", "bangla_ayahs_count" => "আয়াত-৩"),
         array("id" => 104, "name" => "الهمزة", "english_name" => "Al-Humazah", "english_ayahs_count" => "verse-9", "bangla_name" => "আল-হুমাযাহ্", "bangla_ayahs_count" => "আয়াত-৯"),
         array("id" => 105, "name" => "الفيل", "english_name" => "Al-Fil", "english_ayahs_count" => "verse-5", "bangla_name" => "আল-ফীল", "bangla_ayahs_count" => "আয়াত-৫"),
         array("id" => 106, "name" => "قريش", "english_name" => "Quraish", "english_ayahs_count" => "verse-4", "bangla_name" => "ক্বুরাইশ", "bangla_ayahs_count" => "আয়াত-৪"),
         array("id" => 107, "name" => "الماعون", "english_name" => "Al-Ma'un", "english_ayahs_count" => "verse-7", "bangla_name" => "আল-মা‘ঊন", "bangla_ayahs_count" => "আয়াত-৭"),
         array("id" => 108, "name" => "الكوثر", "english_name" => "Al-Kauthar", "english_ayahs_count" => "verse-3", "bangla_name" => "আল-কাউসার", "bangla_ayahs_count" => "আয়াত-৩"),
         array("id" => 109, "name" => "الكافرون", "english_name" => "Al-Kafirun", "english_ayahs_count" => "verse-6", "bangla_name" => "আল-কাফিরূন", "bangla_ayahs_count" => "আয়াত-৬"),
         array("id" => 110, "name" => "النصر", "english_name" => "An-Nasr", "english_ayahs_count" => "verse-3", "bangla_name" => "আন-নাসর", "bangla_ayahs_count" => "আয়াত-৩"),
         array("id" => 111, "name" => "المسد", "english_name" => "Al-Masad", "english_ayahs_count" => "verse-5", "bangla_name" => "আল-মাসাদ", "bangla_ayahs_count" => "আয়াত-৫"),
         array("id" => 112, "name" => "الإخلاص", "english_name" => "Al-Ikhlas", "english_ayahs_count" => "verse-4", "bangla_name" => "আল-ইখলাস", "bangla_ayahs_count" => "আয়াত-৪"),
         array("id" => 113, "name" => "الفلق", "english_name" => "Al-Falaq", "english_ayahs_count" => "verse-5", "bangla_name" => "আল-ফালাক্ব", "bangla_ayahs_count" => "আয়াত-৫"),
         array("id" => 114, "name" => "الناس", "english_name" => "An-Nas", "english_ayahs_count" => "verse-6", "bangla_name" => "আন-নাস", "bangla_ayahs_count" => "আয়াত-৬"),
      );

      SuraList::create([
         'lang_code' => 'eng',
         'sura_list' => json_encode($suraList)
      ]);
   }
}
